[rotor]
radius = 12.5e-3      # Rotor radius [m]

I_xx = 7.085371e-2 # Mass moment of inertia component [kg*m^2]
I_yy = 7.085371e-2 # Mass moment of inertia component [kg*m^2]
I_zz = 0.106132e-2 # Mass moment of inertia component [kg*m^2]

k_xx = 3.09e4      # Stiffness of the magnetic bearing in x [N/m]
k_yy = 3.09e4      # Stiffness of the magnetic bearing in y [N/m]
k_xy = -2.456e3    # Cross stiffness term [N/m]
k_yx = -292        # Cross stiffness term [N/m]

d0_xx = 40.9       # Damping coefficient in x at theta = 0 [N*s/m]
d_xx  = 8.48       # Damping coefficient in x [N*s/m]
d_yy  = 7.7        # Damping coefficient in y [N*s/m]

l_OM = 171.7e-3    # Position vector, pivot point to the PMB [m]
l_OG = 195.9e-3    # Position vector, pivot point to centre of gravity [m]
l_OD = 259.7e-3    # Position vector, pivot point to the disc [m]
l_OC = 428.7e-3    # Position vector, pivot point to contact point [m]
l_OE = 72.5e-3     # Position vector, pivot point to excitation point [m]

[houses]
radius = 14.5e-3      # Stator radius [m]

m_ih = 1.79        # Inner house mass [kg]
m_mh = 8.44        # Middle house mass [kg]

k_ft1 = 8.42e6     # Stiffness of the force transducer [N/m]
k_ft2 = 1.26e7     # Stiffness of the force transducer [N/m]

k_vg = 9.709e8     # Stiffness of vertical beams [N/m]
k_hg = 1.41e9      # Stiffness of horizontal beams [N/m]

d_vg = 2168        # Damping coefficient of vertical beams [Ns/m]
d_hg = 12983       # Damping coefficient of horizontal beams [Ns/m]

l_OIH = 428.7e-3   # Position vector, pivot point to inner house [m]
l_OMH = 428.7e-3   # Position vector, pivot point to middle [m]

[unbalance]
e_x =  0.027       # Unbalance parameter [m]
e_y = -0.072       # Unbalance parameter [m]
m0  = 1e-3         # Unbalance mass [kg]

